package com.fwzx.photovoltaicdatacollect.pojo;

public class CoefficientOfPowerpredictionmodel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coefficient_of_powerpredictionmodel.coefficient_one
     *
     * @mbg.generated Mon Jan 21 09:30:40 CST 2019
     */
    private Double coefficientOne;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coefficient_of_powerpredictionmodel.coefficient_two
     *
     * @mbg.generated Mon Jan 21 09:30:40 CST 2019
     */
    private Double coefficientTwo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coefficient_of_powerpredictionmodel.coefficient_three
     *
     * @mbg.generated Mon Jan 21 09:30:40 CST 2019
     */
    private Double coefficientThree;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coefficient_of_powerpredictionmodel.coefficient_one
     *
     * @return the value of coefficient_of_powerpredictionmodel.coefficient_one
     *
     * @mbg.generated Mon Jan 21 09:30:40 CST 2019
     */
    public Double getCoefficientOne() {
        return coefficientOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coefficient_of_powerpredictionmodel.coefficient_one
     *
     * @param coefficientOne the value for coefficient_of_powerpredictionmodel.coefficient_one
     *
     * @mbg.generated Mon Jan 21 09:30:40 CST 2019
     */
    public void setCoefficientOne(Double coefficientOne) {
        this.coefficientOne = coefficientOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coefficient_of_powerpredictionmodel.coefficient_two
     *
     * @return the value of coefficient_of_powerpredictionmodel.coefficient_two
     *
     * @mbg.generated Mon Jan 21 09:30:40 CST 2019
     */
    public Double getCoefficientTwo() {
        return coefficientTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coefficient_of_powerpredictionmodel.coefficient_two
     *
     * @param coefficientTwo the value for coefficient_of_powerpredictionmodel.coefficient_two
     *
     * @mbg.generated Mon Jan 21 09:30:40 CST 2019
     */
    public void setCoefficientTwo(Double coefficientTwo) {
        this.coefficientTwo = coefficientTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coefficient_of_powerpredictionmodel.coefficient_three
     *
     * @return the value of coefficient_of_powerpredictionmodel.coefficient_three
     *
     * @mbg.generated Mon Jan 21 09:30:40 CST 2019
     */
    public Double getCoefficientThree() {
        return coefficientThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coefficient_of_powerpredictionmodel.coefficient_three
     *
     * @param coefficientThree the value for coefficient_of_powerpredictionmodel.coefficient_three
     *
     * @mbg.generated Mon Jan 21 09:30:40 CST 2019
     */
    public void setCoefficientThree(Double coefficientThree) {
        this.coefficientThree = coefficientThree;
    }
}