package com.fwzx.photovoltaicdatacollect.pojo;

import java.util.Date;

public class ForecastDataRt {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forecast_data_rt.data_time
     *
     * @mbg.generated Thu Jan 17 12:57:15 CST 2019
     */
    private Date dataTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forecast_data_rt.total_radiation
     *
     * @mbg.generated Thu Jan 17 12:57:15 CST 2019
     */
    private Double totalRadiation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forecast_data_rt.scatt_radiation
     *
     * @mbg.generated Thu Jan 17 12:57:15 CST 2019
     */
    private Double scattRadiation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forecast_data_rt.verti_radiation
     *
     * @mbg.generated Thu Jan 17 12:57:15 CST 2019
     */
    private Double vertiRadiation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forecast_data_rt.wind_s
     *
     * @mbg.generated Thu Jan 17 12:57:15 CST 2019
     */
    private Double windS;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forecast_data_rt.wind_d
     *
     * @mbg.generated Thu Jan 17 12:57:15 CST 2019
     */
    private Double windD;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forecast_data_rt.tem
     *
     * @mbg.generated Thu Jan 17 12:57:15 CST 2019
     */
    private Double tem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forecast_data_rt.humi
     *
     * @mbg.generated Thu Jan 17 12:57:15 CST 2019
     */
    private Double humi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column forecast_data_rt.press
     *
     * @mbg.generated Thu Jan 17 12:57:15 CST 2019
     */
    private Double press;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forecast_data_rt.data_time
     *
     * @return the value of forecast_data_rt.data_time
     *
     * @mbg.generated Thu Jan 17 12:57:15 CST 2019
     */
    public Date getDataTime() {
        return dataTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forecast_data_rt.data_time
     *
     * @param dataTime the value for forecast_data_rt.data_time
     *
     * @mbg.generated Thu Jan 17 12:57:15 CST 2019
     */
    public void setDataTime(Date dataTime) {
        this.dataTime = dataTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forecast_data_rt.total_radiation
     *
     * @return the value of forecast_data_rt.total_radiation
     *
     * @mbg.generated Thu Jan 17 12:57:15 CST 2019
     */
    public Double getTotalRadiation() {
        return totalRadiation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forecast_data_rt.total_radiation
     *
     * @param totalRadiation the value for forecast_data_rt.total_radiation
     *
     * @mbg.generated Thu Jan 17 12:57:15 CST 2019
     */
    public void setTotalRadiation(Double totalRadiation) {
        this.totalRadiation = totalRadiation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forecast_data_rt.scatt_radiation
     *
     * @return the value of forecast_data_rt.scatt_radiation
     *
     * @mbg.generated Thu Jan 17 12:57:15 CST 2019
     */
    public Double getScattRadiation() {
        return scattRadiation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forecast_data_rt.scatt_radiation
     *
     * @param scattRadiation the value for forecast_data_rt.scatt_radiation
     *
     * @mbg.generated Thu Jan 17 12:57:15 CST 2019
     */
    public void setScattRadiation(Double scattRadiation) {
        this.scattRadiation = scattRadiation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forecast_data_rt.verti_radiation
     *
     * @return the value of forecast_data_rt.verti_radiation
     *
     * @mbg.generated Thu Jan 17 12:57:15 CST 2019
     */
    public Double getVertiRadiation() {
        return vertiRadiation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forecast_data_rt.verti_radiation
     *
     * @param vertiRadiation the value for forecast_data_rt.verti_radiation
     *
     * @mbg.generated Thu Jan 17 12:57:15 CST 2019
     */
    public void setVertiRadiation(Double vertiRadiation) {
        this.vertiRadiation = vertiRadiation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forecast_data_rt.wind_s
     *
     * @return the value of forecast_data_rt.wind_s
     *
     * @mbg.generated Thu Jan 17 12:57:15 CST 2019
     */
    public Double getWindS() {
        return windS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forecast_data_rt.wind_s
     *
     * @param windS the value for forecast_data_rt.wind_s
     *
     * @mbg.generated Thu Jan 17 12:57:15 CST 2019
     */
    public void setWindS(Double windS) {
        this.windS = windS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forecast_data_rt.wind_d
     *
     * @return the value of forecast_data_rt.wind_d
     *
     * @mbg.generated Thu Jan 17 12:57:15 CST 2019
     */
    public Double getWindD() {
        return windD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forecast_data_rt.wind_d
     *
     * @param windD the value for forecast_data_rt.wind_d
     *
     * @mbg.generated Thu Jan 17 12:57:15 CST 2019
     */
    public void setWindD(Double windD) {
        this.windD = windD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forecast_data_rt.tem
     *
     * @return the value of forecast_data_rt.tem
     *
     * @mbg.generated Thu Jan 17 12:57:15 CST 2019
     */
    public Double getTem() {
        return tem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forecast_data_rt.tem
     *
     * @param tem the value for forecast_data_rt.tem
     *
     * @mbg.generated Thu Jan 17 12:57:15 CST 2019
     */
    public void setTem(Double tem) {
        this.tem = tem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forecast_data_rt.humi
     *
     * @return the value of forecast_data_rt.humi
     *
     * @mbg.generated Thu Jan 17 12:57:15 CST 2019
     */
    public Double getHumi() {
        return humi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forecast_data_rt.humi
     *
     * @param humi the value for forecast_data_rt.humi
     *
     * @mbg.generated Thu Jan 17 12:57:15 CST 2019
     */
    public void setHumi(Double humi) {
        this.humi = humi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column forecast_data_rt.press
     *
     * @return the value of forecast_data_rt.press
     *
     * @mbg.generated Thu Jan 17 12:57:15 CST 2019
     */
    public Double getPress() {
        return press;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column forecast_data_rt.press
     *
     * @param press the value for forecast_data_rt.press
     *
     * @mbg.generated Thu Jan 17 12:57:15 CST 2019
     */
    public void setPress(Double press) {
        this.press = press;
    }
}