package com.fwzx.photovoltaicdatacollect.pojo;

import java.util.Date;

public class PhotovoltaicBp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photovoltaic_bp.id
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photovoltaic_bp.s_number
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    private Integer sNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photovoltaic_bp.p_name
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    private String pName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photovoltaic_bp.p_company
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    private String pCompany;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photovoltaic_bp.p_content
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    private String pContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photovoltaic_bp.p_site
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    private String pSite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photovoltaic_bp.p_longitude
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    private Double pLongitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photovoltaic_bp.p_latitude
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    private Double pLatitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photovoltaic_bp.p_area
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    private Double pArea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photovoltaic_bp.p_capacity
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    private Double pCapacity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photovoltaic_bp.pd_name
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    private String pdName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photovoltaic_bp.pg_line
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    private String pgLine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photovoltaic_bp.pv_rade
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    private String pvRade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photovoltaic_bp.pi_name
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    private String piName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photovoltaic_bp.remarks
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photovoltaic_bp.createtime
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photovoltaic_bp.id
     *
     * @return the value of photovoltaic_bp.id
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photovoltaic_bp.id
     *
     * @param id the value for photovoltaic_bp.id
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photovoltaic_bp.s_number
     *
     * @return the value of photovoltaic_bp.s_number
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    public Integer getsNumber() {
        return sNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photovoltaic_bp.s_number
     *
     * @param sNumber the value for photovoltaic_bp.s_number
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    public void setsNumber(Integer sNumber) {
        this.sNumber = sNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photovoltaic_bp.p_name
     *
     * @return the value of photovoltaic_bp.p_name
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    public String getpName() {
        return pName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photovoltaic_bp.p_name
     *
     * @param pName the value for photovoltaic_bp.p_name
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    public void setpName(String pName) {
        this.pName = pName == null ? null : pName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photovoltaic_bp.p_company
     *
     * @return the value of photovoltaic_bp.p_company
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    public String getpCompany() {
        return pCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photovoltaic_bp.p_company
     *
     * @param pCompany the value for photovoltaic_bp.p_company
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    public void setpCompany(String pCompany) {
        this.pCompany = pCompany == null ? null : pCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photovoltaic_bp.p_content
     *
     * @return the value of photovoltaic_bp.p_content
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    public String getpContent() {
        return pContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photovoltaic_bp.p_content
     *
     * @param pContent the value for photovoltaic_bp.p_content
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    public void setpContent(String pContent) {
        this.pContent = pContent == null ? null : pContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photovoltaic_bp.p_site
     *
     * @return the value of photovoltaic_bp.p_site
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    public String getpSite() {
        return pSite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photovoltaic_bp.p_site
     *
     * @param pSite the value for photovoltaic_bp.p_site
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    public void setpSite(String pSite) {
        this.pSite = pSite == null ? null : pSite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photovoltaic_bp.p_longitude
     *
     * @return the value of photovoltaic_bp.p_longitude
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    public Double getpLongitude() {
        return pLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photovoltaic_bp.p_longitude
     *
     * @param pLongitude the value for photovoltaic_bp.p_longitude
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    public void setpLongitude(Double pLongitude) {
        this.pLongitude = pLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photovoltaic_bp.p_latitude
     *
     * @return the value of photovoltaic_bp.p_latitude
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    public Double getpLatitude() {
        return pLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photovoltaic_bp.p_latitude
     *
     * @param pLatitude the value for photovoltaic_bp.p_latitude
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    public void setpLatitude(Double pLatitude) {
        this.pLatitude = pLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photovoltaic_bp.p_area
     *
     * @return the value of photovoltaic_bp.p_area
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    public Double getpArea() {
        return pArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photovoltaic_bp.p_area
     *
     * @param pArea the value for photovoltaic_bp.p_area
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    public void setpArea(Double pArea) {
        this.pArea = pArea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photovoltaic_bp.p_capacity
     *
     * @return the value of photovoltaic_bp.p_capacity
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    public Double getpCapacity() {
        return pCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photovoltaic_bp.p_capacity
     *
     * @param pCapacity the value for photovoltaic_bp.p_capacity
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    public void setpCapacity(Double pCapacity) {
        this.pCapacity = pCapacity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photovoltaic_bp.pd_name
     *
     * @return the value of photovoltaic_bp.pd_name
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    public String getPdName() {
        return pdName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photovoltaic_bp.pd_name
     *
     * @param pdName the value for photovoltaic_bp.pd_name
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    public void setPdName(String pdName) {
        this.pdName = pdName == null ? null : pdName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photovoltaic_bp.pg_line
     *
     * @return the value of photovoltaic_bp.pg_line
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    public String getPgLine() {
        return pgLine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photovoltaic_bp.pg_line
     *
     * @param pgLine the value for photovoltaic_bp.pg_line
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    public void setPgLine(String pgLine) {
        this.pgLine = pgLine == null ? null : pgLine.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photovoltaic_bp.pv_rade
     *
     * @return the value of photovoltaic_bp.pv_rade
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    public String getPvRade() {
        return pvRade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photovoltaic_bp.pv_rade
     *
     * @param pvRade the value for photovoltaic_bp.pv_rade
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    public void setPvRade(String pvRade) {
        this.pvRade = pvRade == null ? null : pvRade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photovoltaic_bp.pi_name
     *
     * @return the value of photovoltaic_bp.pi_name
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    public String getPiName() {
        return piName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photovoltaic_bp.pi_name
     *
     * @param piName the value for photovoltaic_bp.pi_name
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    public void setPiName(String piName) {
        this.piName = piName == null ? null : piName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photovoltaic_bp.remarks
     *
     * @return the value of photovoltaic_bp.remarks
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photovoltaic_bp.remarks
     *
     * @param remarks the value for photovoltaic_bp.remarks
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photovoltaic_bp.createtime
     *
     * @return the value of photovoltaic_bp.createtime
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photovoltaic_bp.createtime
     *
     * @param createtime the value for photovoltaic_bp.createtime
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}