package com.fwzx.photovoltaicdatacollect.pojo;

import java.util.Date;


public class PhotoActData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo_act_data.id
     *
     * @mbg.generated Mon Jan 21 11:43:01 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo_act_data.get_time
     *
     * @mbg.generated Mon Jan 21 11:43:01 CST 2019
     */
    private Date getTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo_act_data.inst_radiation
     *
     * @mbg.generated Mon Jan 21 11:43:01 CST 2019
     */
    private Double instRadiation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo_act_data.wind_s
     *
     * @mbg.generated Mon Jan 21 11:43:01 CST 2019
     */
    private Double windS;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo_act_data.wind_d
     *
     * @mbg.generated Mon Jan 21 11:43:01 CST 2019
     */
    private Double windD;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo_act_data.tem
     *
     * @mbg.generated Mon Jan 21 11:43:01 CST 2019
     */
    private Double tem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo_act_data.humi
     *
     * @mbg.generated Mon Jan 21 11:43:01 CST 2019
     */
    private Double humi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo_act_data.press
     *
     * @mbg.generated Mon Jan 21 11:43:01 CST 2019
     */
    private Double press;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo_act_data.pre_power
     *
     * @mbg.generated Mon Jan 21 11:43:01 CST 2019
     */
    private Double prePower;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo_act_data.act_power
     *
     * @mbg.generated Mon Jan 21 11:43:01 CST 2019
     */
    private Double actPower;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo_act_data.entry_time
     *
     * @mbg.generated Mon Jan 21 11:43:01 CST 2019
     */
    private Date entryTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo_act_data.id
     *
     * @return the value of photo_act_data.id
     *
     * @mbg.generated Mon Jan 21 11:43:01 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo_act_data.id
     *
     * @param id the value for photo_act_data.id
     *
     * @mbg.generated Mon Jan 21 11:43:01 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo_act_data.get_time
     *
     * @return the value of photo_act_data.get_time
     *
     * @mbg.generated Mon Jan 21 11:43:01 CST 2019
     */
    public Date getGetTime() {
        return getTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo_act_data.get_time
     *
     * @param getTime the value for photo_act_data.get_time
     *
     * @mbg.generated Mon Jan 21 11:43:01 CST 2019
     */
    public void setGetTime(Date getTime) {
        this.getTime = getTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo_act_data.inst_radiation
     *
     * @return the value of photo_act_data.inst_radiation
     *
     * @mbg.generated Mon Jan 21 11:43:01 CST 2019
     */
    public Double getInstRadiation() {
        return instRadiation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo_act_data.inst_radiation
     *
     * @param instRadiation the value for photo_act_data.inst_radiation
     *
     * @mbg.generated Mon Jan 21 11:43:01 CST 2019
     */
    public void setInstRadiation(Double instRadiation) {
        this.instRadiation = instRadiation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo_act_data.wind_s
     *
     * @return the value of photo_act_data.wind_s
     *
     * @mbg.generated Mon Jan 21 11:43:01 CST 2019
     */
    public Double getWindS() {
        return windS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo_act_data.wind_s
     *
     * @param windS the value for photo_act_data.wind_s
     *
     * @mbg.generated Mon Jan 21 11:43:01 CST 2019
     */
    public void setWindS(Double windS) {
        this.windS = windS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo_act_data.wind_d
     *
     * @return the value of photo_act_data.wind_d
     *
     * @mbg.generated Mon Jan 21 11:43:01 CST 2019
     */
    public Double getWindD() {
        return windD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo_act_data.wind_d
     *
     * @param windD the value for photo_act_data.wind_d
     *
     * @mbg.generated Mon Jan 21 11:43:01 CST 2019
     */
    public void setWindD(Double windD) {
        this.windD = windD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo_act_data.tem
     *
     * @return the value of photo_act_data.tem
     *
     * @mbg.generated Mon Jan 21 11:43:01 CST 2019
     */
    public Double getTem() {
        return tem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo_act_data.tem
     *
     * @param tem the value for photo_act_data.tem
     *
     * @mbg.generated Mon Jan 21 11:43:01 CST 2019
     */
    public void setTem(Double tem) {
        this.tem = tem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo_act_data.humi
     *
     * @return the value of photo_act_data.humi
     *
     * @mbg.generated Mon Jan 21 11:43:01 CST 2019
     */
    public Double getHumi() {
        return humi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo_act_data.humi
     *
     * @param humi the value for photo_act_data.humi
     *
     * @mbg.generated Mon Jan 21 11:43:01 CST 2019
     */
    public void setHumi(Double humi) {
        this.humi = humi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo_act_data.press
     *
     * @return the value of photo_act_data.press
     *
     * @mbg.generated Mon Jan 21 11:43:01 CST 2019
     */
    public Double getPress() {
        return press;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo_act_data.press
     *
     * @param press the value for photo_act_data.press
     *
     * @mbg.generated Mon Jan 21 11:43:01 CST 2019
     */
    public void setPress(Double press) {
        this.press = press;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo_act_data.pre_power
     *
     * @return the value of photo_act_data.pre_power
     *
     * @mbg.generated Mon Jan 21 11:43:01 CST 2019
     */
    public Double getPrePower() {
        return prePower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo_act_data.pre_power
     *
     * @param prePower the value for photo_act_data.pre_power
     *
     * @mbg.generated Mon Jan 21 11:43:01 CST 2019
     */
    public void setPrePower(Double prePower) {
        this.prePower = prePower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo_act_data.act_power
     *
     * @return the value of photo_act_data.act_power
     *
     * @mbg.generated Mon Jan 21 11:43:01 CST 2019
     */
    public Double getActPower() {
        return actPower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo_act_data.act_power
     *
     * @param actPower the value for photo_act_data.act_power
     *
     * @mbg.generated Mon Jan 21 11:43:01 CST 2019
     */
    public void setActPower(Double actPower) {
        this.actPower = actPower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo_act_data.entry_time
     *
     * @return the value of photo_act_data.entry_time
     *
     * @mbg.generated Mon Jan 21 11:43:01 CST 2019
     */
    public Date getEntryTime() {
        return entryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo_act_data.entry_time
     *
     * @param entryTime the value for photo_act_data.entry_time
     *
     * @mbg.generated Mon Jan 21 11:43:01 CST 2019
     */
    public void setEntryTime(Date entryTime) {
        this.entryTime = entryTime;
    }

	@Override
	public String toString() {
		return "PhotoActData [id=" + id + ", getTime=" + getTime + ", instRadiation=" + instRadiation + ", windS="
				+ windS + ", windD=" + windD + ", tem=" + tem + ", humi=" + humi + ", press=" + press + ", prePower="
				+ prePower + ", actPower=" + actPower + ", entryTime=" + entryTime + "]";
	}
    
    
}