package com.fwzx.photovoltaicdatacollect.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PhotovoltaicBpExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table photovoltaic_bp
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table photovoltaic_bp
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table photovoltaic_bp
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photovoltaic_bp
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    public PhotovoltaicBpExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photovoltaic_bp
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photovoltaic_bp
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photovoltaic_bp
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photovoltaic_bp
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photovoltaic_bp
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photovoltaic_bp
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photovoltaic_bp
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photovoltaic_bp
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photovoltaic_bp
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photovoltaic_bp
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table photovoltaic_bp
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSNumberIsNull() {
            addCriterion("s_number is null");
            return (Criteria) this;
        }

        public Criteria andSNumberIsNotNull() {
            addCriterion("s_number is not null");
            return (Criteria) this;
        }

        public Criteria andSNumberEqualTo(Integer value) {
            addCriterion("s_number =", value, "sNumber");
            return (Criteria) this;
        }

        public Criteria andSNumberNotEqualTo(Integer value) {
            addCriterion("s_number <>", value, "sNumber");
            return (Criteria) this;
        }

        public Criteria andSNumberGreaterThan(Integer value) {
            addCriterion("s_number >", value, "sNumber");
            return (Criteria) this;
        }

        public Criteria andSNumberGreaterThanOrEqualTo(Integer value) {
            addCriterion("s_number >=", value, "sNumber");
            return (Criteria) this;
        }

        public Criteria andSNumberLessThan(Integer value) {
            addCriterion("s_number <", value, "sNumber");
            return (Criteria) this;
        }

        public Criteria andSNumberLessThanOrEqualTo(Integer value) {
            addCriterion("s_number <=", value, "sNumber");
            return (Criteria) this;
        }

        public Criteria andSNumberIn(List<Integer> values) {
            addCriterion("s_number in", values, "sNumber");
            return (Criteria) this;
        }

        public Criteria andSNumberNotIn(List<Integer> values) {
            addCriterion("s_number not in", values, "sNumber");
            return (Criteria) this;
        }

        public Criteria andSNumberBetween(Integer value1, Integer value2) {
            addCriterion("s_number between", value1, value2, "sNumber");
            return (Criteria) this;
        }

        public Criteria andSNumberNotBetween(Integer value1, Integer value2) {
            addCriterion("s_number not between", value1, value2, "sNumber");
            return (Criteria) this;
        }

        public Criteria andPNameIsNull() {
            addCriterion("p_name is null");
            return (Criteria) this;
        }

        public Criteria andPNameIsNotNull() {
            addCriterion("p_name is not null");
            return (Criteria) this;
        }

        public Criteria andPNameEqualTo(String value) {
            addCriterion("p_name =", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameNotEqualTo(String value) {
            addCriterion("p_name <>", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameGreaterThan(String value) {
            addCriterion("p_name >", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameGreaterThanOrEqualTo(String value) {
            addCriterion("p_name >=", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameLessThan(String value) {
            addCriterion("p_name <", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameLessThanOrEqualTo(String value) {
            addCriterion("p_name <=", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameLike(String value) {
            addCriterion("p_name like", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameNotLike(String value) {
            addCriterion("p_name not like", value, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameIn(List<String> values) {
            addCriterion("p_name in", values, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameNotIn(List<String> values) {
            addCriterion("p_name not in", values, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameBetween(String value1, String value2) {
            addCriterion("p_name between", value1, value2, "pName");
            return (Criteria) this;
        }

        public Criteria andPNameNotBetween(String value1, String value2) {
            addCriterion("p_name not between", value1, value2, "pName");
            return (Criteria) this;
        }

        public Criteria andPCompanyIsNull() {
            addCriterion("p_company is null");
            return (Criteria) this;
        }

        public Criteria andPCompanyIsNotNull() {
            addCriterion("p_company is not null");
            return (Criteria) this;
        }

        public Criteria andPCompanyEqualTo(String value) {
            addCriterion("p_company =", value, "pCompany");
            return (Criteria) this;
        }

        public Criteria andPCompanyNotEqualTo(String value) {
            addCriterion("p_company <>", value, "pCompany");
            return (Criteria) this;
        }

        public Criteria andPCompanyGreaterThan(String value) {
            addCriterion("p_company >", value, "pCompany");
            return (Criteria) this;
        }

        public Criteria andPCompanyGreaterThanOrEqualTo(String value) {
            addCriterion("p_company >=", value, "pCompany");
            return (Criteria) this;
        }

        public Criteria andPCompanyLessThan(String value) {
            addCriterion("p_company <", value, "pCompany");
            return (Criteria) this;
        }

        public Criteria andPCompanyLessThanOrEqualTo(String value) {
            addCriterion("p_company <=", value, "pCompany");
            return (Criteria) this;
        }

        public Criteria andPCompanyLike(String value) {
            addCriterion("p_company like", value, "pCompany");
            return (Criteria) this;
        }

        public Criteria andPCompanyNotLike(String value) {
            addCriterion("p_company not like", value, "pCompany");
            return (Criteria) this;
        }

        public Criteria andPCompanyIn(List<String> values) {
            addCriterion("p_company in", values, "pCompany");
            return (Criteria) this;
        }

        public Criteria andPCompanyNotIn(List<String> values) {
            addCriterion("p_company not in", values, "pCompany");
            return (Criteria) this;
        }

        public Criteria andPCompanyBetween(String value1, String value2) {
            addCriterion("p_company between", value1, value2, "pCompany");
            return (Criteria) this;
        }

        public Criteria andPCompanyNotBetween(String value1, String value2) {
            addCriterion("p_company not between", value1, value2, "pCompany");
            return (Criteria) this;
        }

        public Criteria andPContentIsNull() {
            addCriterion("p_content is null");
            return (Criteria) this;
        }

        public Criteria andPContentIsNotNull() {
            addCriterion("p_content is not null");
            return (Criteria) this;
        }

        public Criteria andPContentEqualTo(String value) {
            addCriterion("p_content =", value, "pContent");
            return (Criteria) this;
        }

        public Criteria andPContentNotEqualTo(String value) {
            addCriterion("p_content <>", value, "pContent");
            return (Criteria) this;
        }

        public Criteria andPContentGreaterThan(String value) {
            addCriterion("p_content >", value, "pContent");
            return (Criteria) this;
        }

        public Criteria andPContentGreaterThanOrEqualTo(String value) {
            addCriterion("p_content >=", value, "pContent");
            return (Criteria) this;
        }

        public Criteria andPContentLessThan(String value) {
            addCriterion("p_content <", value, "pContent");
            return (Criteria) this;
        }

        public Criteria andPContentLessThanOrEqualTo(String value) {
            addCriterion("p_content <=", value, "pContent");
            return (Criteria) this;
        }

        public Criteria andPContentLike(String value) {
            addCriterion("p_content like", value, "pContent");
            return (Criteria) this;
        }

        public Criteria andPContentNotLike(String value) {
            addCriterion("p_content not like", value, "pContent");
            return (Criteria) this;
        }

        public Criteria andPContentIn(List<String> values) {
            addCriterion("p_content in", values, "pContent");
            return (Criteria) this;
        }

        public Criteria andPContentNotIn(List<String> values) {
            addCriterion("p_content not in", values, "pContent");
            return (Criteria) this;
        }

        public Criteria andPContentBetween(String value1, String value2) {
            addCriterion("p_content between", value1, value2, "pContent");
            return (Criteria) this;
        }

        public Criteria andPContentNotBetween(String value1, String value2) {
            addCriterion("p_content not between", value1, value2, "pContent");
            return (Criteria) this;
        }

        public Criteria andPSiteIsNull() {
            addCriterion("p_site is null");
            return (Criteria) this;
        }

        public Criteria andPSiteIsNotNull() {
            addCriterion("p_site is not null");
            return (Criteria) this;
        }

        public Criteria andPSiteEqualTo(String value) {
            addCriterion("p_site =", value, "pSite");
            return (Criteria) this;
        }

        public Criteria andPSiteNotEqualTo(String value) {
            addCriterion("p_site <>", value, "pSite");
            return (Criteria) this;
        }

        public Criteria andPSiteGreaterThan(String value) {
            addCriterion("p_site >", value, "pSite");
            return (Criteria) this;
        }

        public Criteria andPSiteGreaterThanOrEqualTo(String value) {
            addCriterion("p_site >=", value, "pSite");
            return (Criteria) this;
        }

        public Criteria andPSiteLessThan(String value) {
            addCriterion("p_site <", value, "pSite");
            return (Criteria) this;
        }

        public Criteria andPSiteLessThanOrEqualTo(String value) {
            addCriterion("p_site <=", value, "pSite");
            return (Criteria) this;
        }

        public Criteria andPSiteLike(String value) {
            addCriterion("p_site like", value, "pSite");
            return (Criteria) this;
        }

        public Criteria andPSiteNotLike(String value) {
            addCriterion("p_site not like", value, "pSite");
            return (Criteria) this;
        }

        public Criteria andPSiteIn(List<String> values) {
            addCriterion("p_site in", values, "pSite");
            return (Criteria) this;
        }

        public Criteria andPSiteNotIn(List<String> values) {
            addCriterion("p_site not in", values, "pSite");
            return (Criteria) this;
        }

        public Criteria andPSiteBetween(String value1, String value2) {
            addCriterion("p_site between", value1, value2, "pSite");
            return (Criteria) this;
        }

        public Criteria andPSiteNotBetween(String value1, String value2) {
            addCriterion("p_site not between", value1, value2, "pSite");
            return (Criteria) this;
        }

        public Criteria andPLongitudeIsNull() {
            addCriterion("p_longitude is null");
            return (Criteria) this;
        }

        public Criteria andPLongitudeIsNotNull() {
            addCriterion("p_longitude is not null");
            return (Criteria) this;
        }

        public Criteria andPLongitudeEqualTo(Double value) {
            addCriterion("p_longitude =", value, "pLongitude");
            return (Criteria) this;
        }

        public Criteria andPLongitudeNotEqualTo(Double value) {
            addCriterion("p_longitude <>", value, "pLongitude");
            return (Criteria) this;
        }

        public Criteria andPLongitudeGreaterThan(Double value) {
            addCriterion("p_longitude >", value, "pLongitude");
            return (Criteria) this;
        }

        public Criteria andPLongitudeGreaterThanOrEqualTo(Double value) {
            addCriterion("p_longitude >=", value, "pLongitude");
            return (Criteria) this;
        }

        public Criteria andPLongitudeLessThan(Double value) {
            addCriterion("p_longitude <", value, "pLongitude");
            return (Criteria) this;
        }

        public Criteria andPLongitudeLessThanOrEqualTo(Double value) {
            addCriterion("p_longitude <=", value, "pLongitude");
            return (Criteria) this;
        }

        public Criteria andPLongitudeIn(List<Double> values) {
            addCriterion("p_longitude in", values, "pLongitude");
            return (Criteria) this;
        }

        public Criteria andPLongitudeNotIn(List<Double> values) {
            addCriterion("p_longitude not in", values, "pLongitude");
            return (Criteria) this;
        }

        public Criteria andPLongitudeBetween(Double value1, Double value2) {
            addCriterion("p_longitude between", value1, value2, "pLongitude");
            return (Criteria) this;
        }

        public Criteria andPLongitudeNotBetween(Double value1, Double value2) {
            addCriterion("p_longitude not between", value1, value2, "pLongitude");
            return (Criteria) this;
        }

        public Criteria andPLatitudeIsNull() {
            addCriterion("p_latitude is null");
            return (Criteria) this;
        }

        public Criteria andPLatitudeIsNotNull() {
            addCriterion("p_latitude is not null");
            return (Criteria) this;
        }

        public Criteria andPLatitudeEqualTo(Double value) {
            addCriterion("p_latitude =", value, "pLatitude");
            return (Criteria) this;
        }

        public Criteria andPLatitudeNotEqualTo(Double value) {
            addCriterion("p_latitude <>", value, "pLatitude");
            return (Criteria) this;
        }

        public Criteria andPLatitudeGreaterThan(Double value) {
            addCriterion("p_latitude >", value, "pLatitude");
            return (Criteria) this;
        }

        public Criteria andPLatitudeGreaterThanOrEqualTo(Double value) {
            addCriterion("p_latitude >=", value, "pLatitude");
            return (Criteria) this;
        }

        public Criteria andPLatitudeLessThan(Double value) {
            addCriterion("p_latitude <", value, "pLatitude");
            return (Criteria) this;
        }

        public Criteria andPLatitudeLessThanOrEqualTo(Double value) {
            addCriterion("p_latitude <=", value, "pLatitude");
            return (Criteria) this;
        }

        public Criteria andPLatitudeIn(List<Double> values) {
            addCriterion("p_latitude in", values, "pLatitude");
            return (Criteria) this;
        }

        public Criteria andPLatitudeNotIn(List<Double> values) {
            addCriterion("p_latitude not in", values, "pLatitude");
            return (Criteria) this;
        }

        public Criteria andPLatitudeBetween(Double value1, Double value2) {
            addCriterion("p_latitude between", value1, value2, "pLatitude");
            return (Criteria) this;
        }

        public Criteria andPLatitudeNotBetween(Double value1, Double value2) {
            addCriterion("p_latitude not between", value1, value2, "pLatitude");
            return (Criteria) this;
        }

        public Criteria andPAreaIsNull() {
            addCriterion("p_area is null");
            return (Criteria) this;
        }

        public Criteria andPAreaIsNotNull() {
            addCriterion("p_area is not null");
            return (Criteria) this;
        }

        public Criteria andPAreaEqualTo(Double value) {
            addCriterion("p_area =", value, "pArea");
            return (Criteria) this;
        }

        public Criteria andPAreaNotEqualTo(Double value) {
            addCriterion("p_area <>", value, "pArea");
            return (Criteria) this;
        }

        public Criteria andPAreaGreaterThan(Double value) {
            addCriterion("p_area >", value, "pArea");
            return (Criteria) this;
        }

        public Criteria andPAreaGreaterThanOrEqualTo(Double value) {
            addCriterion("p_area >=", value, "pArea");
            return (Criteria) this;
        }

        public Criteria andPAreaLessThan(Double value) {
            addCriterion("p_area <", value, "pArea");
            return (Criteria) this;
        }

        public Criteria andPAreaLessThanOrEqualTo(Double value) {
            addCriterion("p_area <=", value, "pArea");
            return (Criteria) this;
        }

        public Criteria andPAreaIn(List<Double> values) {
            addCriterion("p_area in", values, "pArea");
            return (Criteria) this;
        }

        public Criteria andPAreaNotIn(List<Double> values) {
            addCriterion("p_area not in", values, "pArea");
            return (Criteria) this;
        }

        public Criteria andPAreaBetween(Double value1, Double value2) {
            addCriterion("p_area between", value1, value2, "pArea");
            return (Criteria) this;
        }

        public Criteria andPAreaNotBetween(Double value1, Double value2) {
            addCriterion("p_area not between", value1, value2, "pArea");
            return (Criteria) this;
        }

        public Criteria andPCapacityIsNull() {
            addCriterion("p_capacity is null");
            return (Criteria) this;
        }

        public Criteria andPCapacityIsNotNull() {
            addCriterion("p_capacity is not null");
            return (Criteria) this;
        }

        public Criteria andPCapacityEqualTo(Double value) {
            addCriterion("p_capacity =", value, "pCapacity");
            return (Criteria) this;
        }

        public Criteria andPCapacityNotEqualTo(Double value) {
            addCriterion("p_capacity <>", value, "pCapacity");
            return (Criteria) this;
        }

        public Criteria andPCapacityGreaterThan(Double value) {
            addCriterion("p_capacity >", value, "pCapacity");
            return (Criteria) this;
        }

        public Criteria andPCapacityGreaterThanOrEqualTo(Double value) {
            addCriterion("p_capacity >=", value, "pCapacity");
            return (Criteria) this;
        }

        public Criteria andPCapacityLessThan(Double value) {
            addCriterion("p_capacity <", value, "pCapacity");
            return (Criteria) this;
        }

        public Criteria andPCapacityLessThanOrEqualTo(Double value) {
            addCriterion("p_capacity <=", value, "pCapacity");
            return (Criteria) this;
        }

        public Criteria andPCapacityIn(List<Double> values) {
            addCriterion("p_capacity in", values, "pCapacity");
            return (Criteria) this;
        }

        public Criteria andPCapacityNotIn(List<Double> values) {
            addCriterion("p_capacity not in", values, "pCapacity");
            return (Criteria) this;
        }

        public Criteria andPCapacityBetween(Double value1, Double value2) {
            addCriterion("p_capacity between", value1, value2, "pCapacity");
            return (Criteria) this;
        }

        public Criteria andPCapacityNotBetween(Double value1, Double value2) {
            addCriterion("p_capacity not between", value1, value2, "pCapacity");
            return (Criteria) this;
        }

        public Criteria andPdNameIsNull() {
            addCriterion("pd_name is null");
            return (Criteria) this;
        }

        public Criteria andPdNameIsNotNull() {
            addCriterion("pd_name is not null");
            return (Criteria) this;
        }

        public Criteria andPdNameEqualTo(String value) {
            addCriterion("pd_name =", value, "pdName");
            return (Criteria) this;
        }

        public Criteria andPdNameNotEqualTo(String value) {
            addCriterion("pd_name <>", value, "pdName");
            return (Criteria) this;
        }

        public Criteria andPdNameGreaterThan(String value) {
            addCriterion("pd_name >", value, "pdName");
            return (Criteria) this;
        }

        public Criteria andPdNameGreaterThanOrEqualTo(String value) {
            addCriterion("pd_name >=", value, "pdName");
            return (Criteria) this;
        }

        public Criteria andPdNameLessThan(String value) {
            addCriterion("pd_name <", value, "pdName");
            return (Criteria) this;
        }

        public Criteria andPdNameLessThanOrEqualTo(String value) {
            addCriterion("pd_name <=", value, "pdName");
            return (Criteria) this;
        }

        public Criteria andPdNameLike(String value) {
            addCriterion("pd_name like", value, "pdName");
            return (Criteria) this;
        }

        public Criteria andPdNameNotLike(String value) {
            addCriterion("pd_name not like", value, "pdName");
            return (Criteria) this;
        }

        public Criteria andPdNameIn(List<String> values) {
            addCriterion("pd_name in", values, "pdName");
            return (Criteria) this;
        }

        public Criteria andPdNameNotIn(List<String> values) {
            addCriterion("pd_name not in", values, "pdName");
            return (Criteria) this;
        }

        public Criteria andPdNameBetween(String value1, String value2) {
            addCriterion("pd_name between", value1, value2, "pdName");
            return (Criteria) this;
        }

        public Criteria andPdNameNotBetween(String value1, String value2) {
            addCriterion("pd_name not between", value1, value2, "pdName");
            return (Criteria) this;
        }

        public Criteria andPgLineIsNull() {
            addCriterion("pg_line is null");
            return (Criteria) this;
        }

        public Criteria andPgLineIsNotNull() {
            addCriterion("pg_line is not null");
            return (Criteria) this;
        }

        public Criteria andPgLineEqualTo(String value) {
            addCriterion("pg_line =", value, "pgLine");
            return (Criteria) this;
        }

        public Criteria andPgLineNotEqualTo(String value) {
            addCriterion("pg_line <>", value, "pgLine");
            return (Criteria) this;
        }

        public Criteria andPgLineGreaterThan(String value) {
            addCriterion("pg_line >", value, "pgLine");
            return (Criteria) this;
        }

        public Criteria andPgLineGreaterThanOrEqualTo(String value) {
            addCriterion("pg_line >=", value, "pgLine");
            return (Criteria) this;
        }

        public Criteria andPgLineLessThan(String value) {
            addCriterion("pg_line <", value, "pgLine");
            return (Criteria) this;
        }

        public Criteria andPgLineLessThanOrEqualTo(String value) {
            addCriterion("pg_line <=", value, "pgLine");
            return (Criteria) this;
        }

        public Criteria andPgLineLike(String value) {
            addCriterion("pg_line like", value, "pgLine");
            return (Criteria) this;
        }

        public Criteria andPgLineNotLike(String value) {
            addCriterion("pg_line not like", value, "pgLine");
            return (Criteria) this;
        }

        public Criteria andPgLineIn(List<String> values) {
            addCriterion("pg_line in", values, "pgLine");
            return (Criteria) this;
        }

        public Criteria andPgLineNotIn(List<String> values) {
            addCriterion("pg_line not in", values, "pgLine");
            return (Criteria) this;
        }

        public Criteria andPgLineBetween(String value1, String value2) {
            addCriterion("pg_line between", value1, value2, "pgLine");
            return (Criteria) this;
        }

        public Criteria andPgLineNotBetween(String value1, String value2) {
            addCriterion("pg_line not between", value1, value2, "pgLine");
            return (Criteria) this;
        }

        public Criteria andPvRadeIsNull() {
            addCriterion("pv_rade is null");
            return (Criteria) this;
        }

        public Criteria andPvRadeIsNotNull() {
            addCriterion("pv_rade is not null");
            return (Criteria) this;
        }

        public Criteria andPvRadeEqualTo(String value) {
            addCriterion("pv_rade =", value, "pvRade");
            return (Criteria) this;
        }

        public Criteria andPvRadeNotEqualTo(String value) {
            addCriterion("pv_rade <>", value, "pvRade");
            return (Criteria) this;
        }

        public Criteria andPvRadeGreaterThan(String value) {
            addCriterion("pv_rade >", value, "pvRade");
            return (Criteria) this;
        }

        public Criteria andPvRadeGreaterThanOrEqualTo(String value) {
            addCriterion("pv_rade >=", value, "pvRade");
            return (Criteria) this;
        }

        public Criteria andPvRadeLessThan(String value) {
            addCriterion("pv_rade <", value, "pvRade");
            return (Criteria) this;
        }

        public Criteria andPvRadeLessThanOrEqualTo(String value) {
            addCriterion("pv_rade <=", value, "pvRade");
            return (Criteria) this;
        }

        public Criteria andPvRadeLike(String value) {
            addCriterion("pv_rade like", value, "pvRade");
            return (Criteria) this;
        }

        public Criteria andPvRadeNotLike(String value) {
            addCriterion("pv_rade not like", value, "pvRade");
            return (Criteria) this;
        }

        public Criteria andPvRadeIn(List<String> values) {
            addCriterion("pv_rade in", values, "pvRade");
            return (Criteria) this;
        }

        public Criteria andPvRadeNotIn(List<String> values) {
            addCriterion("pv_rade not in", values, "pvRade");
            return (Criteria) this;
        }

        public Criteria andPvRadeBetween(String value1, String value2) {
            addCriterion("pv_rade between", value1, value2, "pvRade");
            return (Criteria) this;
        }

        public Criteria andPvRadeNotBetween(String value1, String value2) {
            addCriterion("pv_rade not between", value1, value2, "pvRade");
            return (Criteria) this;
        }

        public Criteria andPiNameIsNull() {
            addCriterion("pi_name is null");
            return (Criteria) this;
        }

        public Criteria andPiNameIsNotNull() {
            addCriterion("pi_name is not null");
            return (Criteria) this;
        }

        public Criteria andPiNameEqualTo(String value) {
            addCriterion("pi_name =", value, "piName");
            return (Criteria) this;
        }

        public Criteria andPiNameNotEqualTo(String value) {
            addCriterion("pi_name <>", value, "piName");
            return (Criteria) this;
        }

        public Criteria andPiNameGreaterThan(String value) {
            addCriterion("pi_name >", value, "piName");
            return (Criteria) this;
        }

        public Criteria andPiNameGreaterThanOrEqualTo(String value) {
            addCriterion("pi_name >=", value, "piName");
            return (Criteria) this;
        }

        public Criteria andPiNameLessThan(String value) {
            addCriterion("pi_name <", value, "piName");
            return (Criteria) this;
        }

        public Criteria andPiNameLessThanOrEqualTo(String value) {
            addCriterion("pi_name <=", value, "piName");
            return (Criteria) this;
        }

        public Criteria andPiNameLike(String value) {
            addCriterion("pi_name like", value, "piName");
            return (Criteria) this;
        }

        public Criteria andPiNameNotLike(String value) {
            addCriterion("pi_name not like", value, "piName");
            return (Criteria) this;
        }

        public Criteria andPiNameIn(List<String> values) {
            addCriterion("pi_name in", values, "piName");
            return (Criteria) this;
        }

        public Criteria andPiNameNotIn(List<String> values) {
            addCriterion("pi_name not in", values, "piName");
            return (Criteria) this;
        }

        public Criteria andPiNameBetween(String value1, String value2) {
            addCriterion("pi_name between", value1, value2, "piName");
            return (Criteria) this;
        }

        public Criteria andPiNameNotBetween(String value1, String value2) {
            addCriterion("pi_name not between", value1, value2, "piName");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNull() {
            addCriterion("remarks is null");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNotNull() {
            addCriterion("remarks is not null");
            return (Criteria) this;
        }

        public Criteria andRemarksEqualTo(String value) {
            addCriterion("remarks =", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotEqualTo(String value) {
            addCriterion("remarks <>", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThan(String value) {
            addCriterion("remarks >", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("remarks >=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThan(String value) {
            addCriterion("remarks <", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThanOrEqualTo(String value) {
            addCriterion("remarks <=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLike(String value) {
            addCriterion("remarks like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotLike(String value) {
            addCriterion("remarks not like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksIn(List<String> values) {
            addCriterion("remarks in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotIn(List<String> values) {
            addCriterion("remarks not in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksBetween(String value1, String value2) {
            addCriterion("remarks between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotBetween(String value1, String value2) {
            addCriterion("remarks not between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createtime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createtime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createtime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createtime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createtime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createtime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createtime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createtime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createtime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createtime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createtime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createtime not between", value1, value2, "createtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table photovoltaic_bp
     *
     * @mbg.generated do_not_delete_during_merge Mon Jan 21 11:12:56 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table photovoltaic_bp
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}