package com.fwzx.photovoltaicdatacollect.pojo;

import java.util.Date;

public class ShortForecFut {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column short_forec_fut.id
     *
     * @mbg.generated Thu Jan 24 09:40:14 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column short_forec_fut.data_time
     *
     * @mbg.generated Thu Jan 24 09:40:14 CST 2019
     */
    private Date dataTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column short_forec_fut.inst_radiation
     *
     * @mbg.generated Thu Jan 24 09:40:14 CST 2019
     */
    private Double instRadiation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column short_forec_fut.wind_s
     *
     * @mbg.generated Thu Jan 24 09:40:14 CST 2019
     */
    private Double windS;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column short_forec_fut.wind_d
     *
     * @mbg.generated Thu Jan 24 09:40:14 CST 2019
     */
    private Double windD;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column short_forec_fut.tem
     *
     * @mbg.generated Thu Jan 24 09:40:14 CST 2019
     */
    private Double tem;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column short_forec_fut.humi
     *
     * @mbg.generated Thu Jan 24 09:40:14 CST 2019
     */
    private Double humi;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column short_forec_fut.press
     *
     * @mbg.generated Thu Jan 24 09:40:14 CST 2019
     */
    private Double press;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column short_forec_fut.power
     *
     * @mbg.generated Thu Jan 24 09:40:14 CST 2019
     */
    private Double power;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column short_forec_fut.entry_time
     *
     * @mbg.generated Thu Jan 24 09:40:14 CST 2019
     */
    private Date entryTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column short_forec_fut.id
     *
     * @return the value of short_forec_fut.id
     *
     * @mbg.generated Thu Jan 24 09:40:14 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column short_forec_fut.id
     *
     * @param id the value for short_forec_fut.id
     *
     * @mbg.generated Thu Jan 24 09:40:14 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column short_forec_fut.data_time
     *
     * @return the value of short_forec_fut.data_time
     *
     * @mbg.generated Thu Jan 24 09:40:14 CST 2019
     */
    public Date getDataTime() {
        return dataTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column short_forec_fut.data_time
     *
     * @param dataTime the value for short_forec_fut.data_time
     *
     * @mbg.generated Thu Jan 24 09:40:14 CST 2019
     */
    public void setDataTime(Date dataTime) {
        this.dataTime = dataTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column short_forec_fut.inst_radiation
     *
     * @return the value of short_forec_fut.inst_radiation
     *
     * @mbg.generated Thu Jan 24 09:40:14 CST 2019
     */
    public Double getInstRadiation() {
        return instRadiation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column short_forec_fut.inst_radiation
     *
     * @param instRadiation the value for short_forec_fut.inst_radiation
     *
     * @mbg.generated Thu Jan 24 09:40:14 CST 2019
     */
    public void setInstRadiation(Double instRadiation) {
        this.instRadiation = instRadiation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column short_forec_fut.wind_s
     *
     * @return the value of short_forec_fut.wind_s
     *
     * @mbg.generated Thu Jan 24 09:40:14 CST 2019
     */
    public Double getWindS() {
        return windS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column short_forec_fut.wind_s
     *
     * @param windS the value for short_forec_fut.wind_s
     *
     * @mbg.generated Thu Jan 24 09:40:14 CST 2019
     */
    public void setWindS(Double windS) {
        this.windS = windS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column short_forec_fut.wind_d
     *
     * @return the value of short_forec_fut.wind_d
     *
     * @mbg.generated Thu Jan 24 09:40:14 CST 2019
     */
    public Double getWindD() {
        return windD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column short_forec_fut.wind_d
     *
     * @param windD the value for short_forec_fut.wind_d
     *
     * @mbg.generated Thu Jan 24 09:40:14 CST 2019
     */
    public void setWindD(Double windD) {
        this.windD = windD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column short_forec_fut.tem
     *
     * @return the value of short_forec_fut.tem
     *
     * @mbg.generated Thu Jan 24 09:40:14 CST 2019
     */
    public Double getTem() {
        return tem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column short_forec_fut.tem
     *
     * @param tem the value for short_forec_fut.tem
     *
     * @mbg.generated Thu Jan 24 09:40:14 CST 2019
     */
    public void setTem(Double tem) {
        this.tem = tem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column short_forec_fut.humi
     *
     * @return the value of short_forec_fut.humi
     *
     * @mbg.generated Thu Jan 24 09:40:14 CST 2019
     */
    public Double getHumi() {
        return humi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column short_forec_fut.humi
     *
     * @param humi the value for short_forec_fut.humi
     *
     * @mbg.generated Thu Jan 24 09:40:14 CST 2019
     */
    public void setHumi(Double humi) {
        this.humi = humi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column short_forec_fut.press
     *
     * @return the value of short_forec_fut.press
     *
     * @mbg.generated Thu Jan 24 09:40:14 CST 2019
     */
    public Double getPress() {
        return press;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column short_forec_fut.press
     *
     * @param press the value for short_forec_fut.press
     *
     * @mbg.generated Thu Jan 24 09:40:14 CST 2019
     */
    public void setPress(Double press) {
        this.press = press;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column short_forec_fut.power
     *
     * @return the value of short_forec_fut.power
     *
     * @mbg.generated Thu Jan 24 09:40:14 CST 2019
     */
    public Double getPower() {
        return power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column short_forec_fut.power
     *
     * @param power the value for short_forec_fut.power
     *
     * @mbg.generated Thu Jan 24 09:40:14 CST 2019
     */
    public void setPower(Double power) {
        this.power = power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column short_forec_fut.entry_time
     *
     * @return the value of short_forec_fut.entry_time
     *
     * @mbg.generated Thu Jan 24 09:40:14 CST 2019
     */
    public Date getEntryTime() {
        return entryTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column short_forec_fut.entry_time
     *
     * @param entryTime the value for short_forec_fut.entry_time
     *
     * @mbg.generated Thu Jan 24 09:40:14 CST 2019
     */
    public void setEntryTime(Date entryTime) {
        this.entryTime = entryTime;
    }
}