package com.fwzx.photovoltaicdatacollect.pojo;

import java.util.Date;

public class SupershortForecHis {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supershort_forec_his.data_time
     *
     * @mbg.generated Mon Jan 21 11:52:44 CST 2019
     */
    private Date dataTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column supershort_forec_his.short_forec
     *
     * @mbg.generated Mon Jan 21 11:52:44 CST 2019
     */
    private Double shortForec;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supershort_forec_his.data_time
     *
     * @return the value of supershort_forec_his.data_time
     *
     * @mbg.generated Mon Jan 21 11:52:44 CST 2019
     */
    public Date getDataTime() {
        return dataTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supershort_forec_his.data_time
     *
     * @param dataTime the value for supershort_forec_his.data_time
     *
     * @mbg.generated Mon Jan 21 11:52:44 CST 2019
     */
    public void setDataTime(Date dataTime) {
        this.dataTime = dataTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column supershort_forec_his.short_forec
     *
     * @return the value of supershort_forec_his.short_forec
     *
     * @mbg.generated Mon Jan 21 11:52:44 CST 2019
     */
    public Double getShortForec() {
        return shortForec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column supershort_forec_his.short_forec
     *
     * @param shortForec the value for supershort_forec_his.short_forec
     *
     * @mbg.generated Mon Jan 21 11:52:44 CST 2019
     */
    public void setShortForec(Double shortForec) {
        this.shortForec = shortForec;
    }
}