package com.fwzx.photovoltaicdatacollect.pojo;

import java.util.Date;

public class SuperaccuPassRate {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column superaccu_pass_rate.id
     *
     * @mbg.generated Tue Jan 29 15:22:02 CST 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column superaccu_pass_rate.data_time
     *
     * @mbg.generated Tue Jan 29 15:22:02 CST 2019
     */
    private Date dataTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column superaccu_pass_rate.root_mesqu_err
     *
     * @mbg.generated Tue Jan 29 15:22:02 CST 2019
     */
    private Double rootMesquErr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column superaccu_pass_rate.avg_abs_err
     *
     * @mbg.generated Tue Jan 29 15:22:02 CST 2019
     */
    private Double avgAbsErr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column superaccu_pass_rate.coeff_corr
     *
     * @mbg.generated Tue Jan 29 15:22:02 CST 2019
     */
    private Double coeffCorr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column superaccu_pass_rate.pass_rate
     *
     * @mbg.generated Tue Jan 29 15:22:02 CST 2019
     */
    private Double passRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column superaccu_pass_rate.passrate_checpower
     *
     * @mbg.generated Tue Jan 29 15:22:02 CST 2019
     */
    private Double passrateChecpower;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column superaccu_pass_rate.accu_rate
     *
     * @mbg.generated Tue Jan 29 15:22:02 CST 2019
     */
    private Double accuRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column superaccu_pass_rate.accurate_checpower
     *
     * @mbg.generated Tue Jan 29 15:22:02 CST 2019
     */
    private Double accurateChecpower;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column superaccu_pass_rate.id
     *
     * @return the value of superaccu_pass_rate.id
     *
     * @mbg.generated Tue Jan 29 15:22:02 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column superaccu_pass_rate.id
     *
     * @param id the value for superaccu_pass_rate.id
     *
     * @mbg.generated Tue Jan 29 15:22:02 CST 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column superaccu_pass_rate.data_time
     *
     * @return the value of superaccu_pass_rate.data_time
     *
     * @mbg.generated Tue Jan 29 15:22:02 CST 2019
     */
    public Date getDataTime() {
        return dataTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column superaccu_pass_rate.data_time
     *
     * @param dataTime the value for superaccu_pass_rate.data_time
     *
     * @mbg.generated Tue Jan 29 15:22:02 CST 2019
     */
    public void setDataTime(Date dataTime) {
        this.dataTime = dataTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column superaccu_pass_rate.root_mesqu_err
     *
     * @return the value of superaccu_pass_rate.root_mesqu_err
     *
     * @mbg.generated Tue Jan 29 15:22:02 CST 2019
     */
    public Double getRootMesquErr() {
        return rootMesquErr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column superaccu_pass_rate.root_mesqu_err
     *
     * @param rootMesquErr the value for superaccu_pass_rate.root_mesqu_err
     *
     * @mbg.generated Tue Jan 29 15:22:02 CST 2019
     */
    public void setRootMesquErr(Double rootMesquErr) {
        this.rootMesquErr = rootMesquErr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column superaccu_pass_rate.avg_abs_err
     *
     * @return the value of superaccu_pass_rate.avg_abs_err
     *
     * @mbg.generated Tue Jan 29 15:22:02 CST 2019
     */
    public Double getAvgAbsErr() {
        return avgAbsErr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column superaccu_pass_rate.avg_abs_err
     *
     * @param avgAbsErr the value for superaccu_pass_rate.avg_abs_err
     *
     * @mbg.generated Tue Jan 29 15:22:02 CST 2019
     */
    public void setAvgAbsErr(Double avgAbsErr) {
        this.avgAbsErr = avgAbsErr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column superaccu_pass_rate.coeff_corr
     *
     * @return the value of superaccu_pass_rate.coeff_corr
     *
     * @mbg.generated Tue Jan 29 15:22:02 CST 2019
     */
    public Double getCoeffCorr() {
        return coeffCorr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column superaccu_pass_rate.coeff_corr
     *
     * @param coeffCorr the value for superaccu_pass_rate.coeff_corr
     *
     * @mbg.generated Tue Jan 29 15:22:02 CST 2019
     */
    public void setCoeffCorr(Double coeffCorr) {
        this.coeffCorr = coeffCorr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column superaccu_pass_rate.pass_rate
     *
     * @return the value of superaccu_pass_rate.pass_rate
     *
     * @mbg.generated Tue Jan 29 15:22:02 CST 2019
     */
    public Double getPassRate() {
        return passRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column superaccu_pass_rate.pass_rate
     *
     * @param passRate the value for superaccu_pass_rate.pass_rate
     *
     * @mbg.generated Tue Jan 29 15:22:02 CST 2019
     */
    public void setPassRate(Double passRate) {
        this.passRate = passRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column superaccu_pass_rate.passrate_checpower
     *
     * @return the value of superaccu_pass_rate.passrate_checpower
     *
     * @mbg.generated Tue Jan 29 15:22:02 CST 2019
     */
    public Double getPassrateChecpower() {
        return passrateChecpower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column superaccu_pass_rate.passrate_checpower
     *
     * @param passrateChecpower the value for superaccu_pass_rate.passrate_checpower
     *
     * @mbg.generated Tue Jan 29 15:22:02 CST 2019
     */
    public void setPassrateChecpower(Double passrateChecpower) {
        this.passrateChecpower = passrateChecpower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column superaccu_pass_rate.accu_rate
     *
     * @return the value of superaccu_pass_rate.accu_rate
     *
     * @mbg.generated Tue Jan 29 15:22:02 CST 2019
     */
    public Double getAccuRate() {
        return accuRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column superaccu_pass_rate.accu_rate
     *
     * @param accuRate the value for superaccu_pass_rate.accu_rate
     *
     * @mbg.generated Tue Jan 29 15:22:02 CST 2019
     */
    public void setAccuRate(Double accuRate) {
        this.accuRate = accuRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column superaccu_pass_rate.accurate_checpower
     *
     * @return the value of superaccu_pass_rate.accurate_checpower
     *
     * @mbg.generated Tue Jan 29 15:22:02 CST 2019
     */
    public Double getAccurateChecpower() {
        return accurateChecpower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column superaccu_pass_rate.accurate_checpower
     *
     * @param accurateChecpower the value for superaccu_pass_rate.accurate_checpower
     *
     * @mbg.generated Tue Jan 29 15:22:02 CST 2019
     */
    public void setAccurateChecpower(Double accurateChecpower) {
        this.accurateChecpower = accurateChecpower;
    }
}