package com.fwzx.photovoltaicdatacollect.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.fwzx.photovoltaicdatacollect.pojo.AccuPassRate;
import com.fwzx.photovoltaicdatacollect.pojo.AccuPassRateExample;

public interface AccuPassRateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accu_pass_rate
     *
     * @mbg.generated Tue Jan 29 11:11:08 CST 2019
     */
    long countByExample(AccuPassRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accu_pass_rate
     *
     * @mbg.generated Tue Jan 29 11:11:08 CST 2019
     */
    int deleteByExample(AccuPassRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accu_pass_rate
     *
     * @mbg.generated Tue Jan 29 11:11:08 CST 2019
     */
    int insert(AccuPassRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accu_pass_rate
     *
     * @mbg.generated Tue Jan 29 11:11:08 CST 2019
     */
    int insertSelective(AccuPassRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accu_pass_rate
     *
     * @mbg.generated Tue Jan 29 11:11:08 CST 2019
     */
    List<AccuPassRate> selectByExample(AccuPassRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accu_pass_rate
     *
     * @mbg.generated Tue Jan 29 11:11:08 CST 2019
     */
    int updateByExampleSelective(@Param("record") AccuPassRate record, @Param("example") AccuPassRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table accu_pass_rate
     *
     * @mbg.generated Tue Jan 29 11:11:08 CST 2019
     */
    int updateByExample(@Param("record") AccuPassRate record, @Param("example") AccuPassRateExample example);
    
    int updatePassRateByDateTime(@Param("apr") AccuPassRate apr);

    AccuPassRate selectByDataTime(@Param("dataTime") String dataTime);

	int updateAccuRateByDateTime(@Param("apr") AccuPassRate apr);
}