package com.fwzx.photovoltaicdatacollect.dao;

import com.fwzx.photovoltaicdatacollect.pojo.CoefficientOfPowerpredictionmodel;
import com.fwzx.photovoltaicdatacollect.pojo.CoefficientOfPowerpredictionmodelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CoefficientOfPowerpredictionmodelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coefficient_of_powerpredictionmodel
     *
     * @mbg.generated Mon Jan 21 09:30:40 CST 2019
     */
    long countByExample(CoefficientOfPowerpredictionmodelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coefficient_of_powerpredictionmodel
     *
     * @mbg.generated Mon Jan 21 09:30:40 CST 2019
     */
    int deleteByExample(CoefficientOfPowerpredictionmodelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coefficient_of_powerpredictionmodel
     *
     * @mbg.generated Mon Jan 21 09:30:40 CST 2019
     */
    int insert(CoefficientOfPowerpredictionmodel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coefficient_of_powerpredictionmodel
     *
     * @mbg.generated Mon Jan 21 09:30:40 CST 2019
     */
    int insertSelective(CoefficientOfPowerpredictionmodel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coefficient_of_powerpredictionmodel
     *
     * @mbg.generated Mon Jan 21 09:30:40 CST 2019
     */
    List<CoefficientOfPowerpredictionmodel> selectByExample(CoefficientOfPowerpredictionmodelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coefficient_of_powerpredictionmodel
     *
     * @mbg.generated Mon Jan 21 09:30:40 CST 2019
     */
    int updateByExampleSelective(@Param("record") CoefficientOfPowerpredictionmodel record, @Param("example") CoefficientOfPowerpredictionmodelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coefficient_of_powerpredictionmodel
     *
     * @mbg.generated Mon Jan 21 09:30:40 CST 2019
     */
    int updateByExample(@Param("record") CoefficientOfPowerpredictionmodel record, @Param("example") CoefficientOfPowerpredictionmodelExample example);

    CoefficientOfPowerpredictionmodel getCoefficient();
}