package com.fwzx.photovoltaicdatacollect.dao;

import com.fwzx.photovoltaicdatacollect.pojo.ForecastDataHis;
import com.fwzx.photovoltaicdatacollect.pojo.ForecastDataHisExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ForecastDataHisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forecast_data_his
     *
     * @mbg.generated Thu Jan 17 15:19:37 CST 2019
     */
    long countByExample(ForecastDataHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forecast_data_his
     *
     * @mbg.generated Thu Jan 17 15:19:37 CST 2019
     */
    int deleteByExample(ForecastDataHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forecast_data_his
     *
     * @mbg.generated Thu Jan 17 15:19:37 CST 2019
     */
    int insert(ForecastDataHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forecast_data_his
     *
     * @mbg.generated Thu Jan 17 15:19:37 CST 2019
     */
    int insertSelective(ForecastDataHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forecast_data_his
     *
     * @mbg.generated Thu Jan 17 15:19:37 CST 2019
     */
    List<ForecastDataHis> selectByExample(ForecastDataHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forecast_data_his
     *
     * @mbg.generated Thu Jan 17 15:19:37 CST 2019
     */
    int updateByExampleSelective(@Param("record") ForecastDataHis record, @Param("example") ForecastDataHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forecast_data_his
     *
     * @mbg.generated Thu Jan 17 15:19:37 CST 2019
     */
    int updateByExample(@Param("record") ForecastDataHis record, @Param("example") ForecastDataHisExample example);

	void deleteRepeatDataByTime(@Param("timeStr") String timeStr);

	void insertDataByStr(@Param("dataSql") String dataSql);
}