package com.fwzx.photovoltaicdatacollect.dao;

import com.fwzx.photovoltaicdatacollect.pojo.ForecastDataRt;
import com.fwzx.photovoltaicdatacollect.pojo.ForecastDataRtExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ForecastDataRtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forecast_data_rt
     *
     * @mbg.generated Thu Jan 17 12:57:15 CST 2019
     */
    long countByExample(ForecastDataRtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forecast_data_rt
     *
     * @mbg.generated Thu Jan 17 12:57:15 CST 2019
     */
    int deleteByExample(ForecastDataRtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forecast_data_rt
     *
     * @mbg.generated Thu Jan 17 12:57:15 CST 2019
     */
    int insert(ForecastDataRt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forecast_data_rt
     *
     * @mbg.generated Thu Jan 17 12:57:15 CST 2019
     */
    int insertSelective(ForecastDataRt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forecast_data_rt
     *
     * @mbg.generated Thu Jan 17 12:57:15 CST 2019
     */
    List<ForecastDataRt> selectByExample(ForecastDataRtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forecast_data_rt
     *
     * @mbg.generated Thu Jan 17 12:57:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") ForecastDataRt record, @Param("example") ForecastDataRtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table forecast_data_rt
     *
     * @mbg.generated Thu Jan 17 12:57:15 CST 2019
     */
    int updateByExample(@Param("record") ForecastDataRt record, @Param("example") ForecastDataRtExample example);
    
    void deleteAllData();
    
    void insertDataByStr(@Param("dataStr") String dataStr);
}