package com.fwzx.photovoltaicdatacollect.dao;

import com.fwzx.photovoltaicdatacollect.pojo.PhotoActData;
import com.fwzx.photovoltaicdatacollect.pojo.PhotoActDataExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface PhotoActDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photo_act_data
     *
     * @mbg.generated Mon Jan 21 11:43:01 CST 2019
     */
    long countByExample(PhotoActDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photo_act_data
     *
     * @mbg.generated Mon Jan 21 11:43:01 CST 2019
     */
    int deleteByExample(PhotoActDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photo_act_data
     *
     * @mbg.generated Mon Jan 21 11:43:01 CST 2019
     */
    int insert(PhotoActData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photo_act_data
     *
     * @mbg.generated Mon Jan 21 11:43:01 CST 2019
     */
    int insertSelective(PhotoActData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photo_act_data
     *
     * @mbg.generated Mon Jan 21 11:43:01 CST 2019
     */
    List<PhotoActData> selectByExample(PhotoActDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photo_act_data
     *
     * @mbg.generated Mon Jan 21 11:43:01 CST 2019
     */
    int updateByExampleSelective(@Param("record") PhotoActData record, @Param("example") PhotoActDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photo_act_data
     *
     * @mbg.generated Mon Jan 21 11:43:01 CST 2019
     */
    int updateByExample(@Param("record") PhotoActData record, @Param("example") PhotoActDataExample example);

	List<PhotoActData> selectPhotoActDataByTime(@Param("beginDate") String beginDate,@Param("endDate") String endDate);

	//select * from photo_act_data where get_time between #{beginDate} and #{endDate} order by get_time
	@Select("select * from photo_act_data where get_time between #{beginDate} and #{endDate} order by get_time")
	List<PhotoActData> selectPhotoActData(@Param("beginDate") String beginDate,@Param("endDate") String endDate);
	
	List<PhotoActData> selectPhotoActDataByTime2(@Param("beginDate") String beginDate,@Param("endDate") String endDate);
}