package com.fwzx.photovoltaicdatacollect.dao;

import com.fwzx.photovoltaicdatacollect.pojo.PhotovoltaicBp;
import com.fwzx.photovoltaicdatacollect.pojo.PhotovoltaicBpExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PhotovoltaicBpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photovoltaic_bp
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    long countByExample(PhotovoltaicBpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photovoltaic_bp
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    int deleteByExample(PhotovoltaicBpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photovoltaic_bp
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    int insert(PhotovoltaicBp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photovoltaic_bp
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    int insertSelective(PhotovoltaicBp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photovoltaic_bp
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    List<PhotovoltaicBp> selectByExample(PhotovoltaicBpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photovoltaic_bp
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") PhotovoltaicBp record, @Param("example") PhotovoltaicBpExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photovoltaic_bp
     *
     * @mbg.generated Mon Jan 21 11:12:56 CST 2019
     */
    int updateByExample(@Param("record") PhotovoltaicBp record, @Param("example") PhotovoltaicBpExample example);

	List<PhotovoltaicBp> queryAll();
}