package com.fwzx.photovoltaicdatacollect.dao;

import com.fwzx.photovoltaicdatacollect.pojo.ShortForecHis;
import com.fwzx.photovoltaicdatacollect.pojo.ShortForecHisExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ShortForecHisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table short_forec_his
     *
     * @mbg.generated Mon Jan 21 09:08:19 CST 2019
     */
    long countByExample(ShortForecHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table short_forec_his
     *
     * @mbg.generated Mon Jan 21 09:08:19 CST 2019
     */
    int deleteByExample(ShortForecHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table short_forec_his
     *
     * @mbg.generated Mon Jan 21 09:08:19 CST 2019
     */
    int insert(ShortForecHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table short_forec_his
     *
     * @mbg.generated Mon Jan 21 09:08:19 CST 2019
     */
    int insertSelective(ShortForecHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table short_forec_his
     *
     * @mbg.generated Mon Jan 21 09:08:19 CST 2019
     */
    List<ShortForecHis> selectByExample(ShortForecHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table short_forec_his
     *
     * @mbg.generated Mon Jan 21 09:08:19 CST 2019
     */
    int updateByExampleSelective(@Param("record") ShortForecHis record, @Param("example") ShortForecHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table short_forec_his
     *
     * @mbg.generated Mon Jan 21 09:08:19 CST 2019
     */
    int updateByExample(@Param("record") ShortForecHis record, @Param("example") ShortForecHisExample example);

	void deleteRepeatDataByTime(@Param("timeStr") String timeStr);

	void insertDataByStr(@Param("dataSql") String dataSql);
}