package com.fwzx.photovoltaicdatacollect.dao;

import com.fwzx.photovoltaicdatacollect.pojo.SupershortForecHis;
import com.fwzx.photovoltaicdatacollect.pojo.SupershortForecHisExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SupershortForecHisMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supershort_forec_his
     *
     * @mbg.generated Thu Jan 24 11:47:13 CST 2019
     */
    long countByExample(SupershortForecHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supershort_forec_his
     *
     * @mbg.generated Thu Jan 24 11:47:13 CST 2019
     */
    int deleteByExample(SupershortForecHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supershort_forec_his
     *
     * @mbg.generated Thu Jan 24 11:47:13 CST 2019
     */
    int insert(SupershortForecHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supershort_forec_his
     *
     * @mbg.generated Thu Jan 24 11:47:13 CST 2019
     */
    int insertSelective(SupershortForecHis record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supershort_forec_his
     *
     * @mbg.generated Thu Jan 24 11:47:13 CST 2019
     */
    List<SupershortForecHis> selectByExample(SupershortForecHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supershort_forec_his
     *
     * @mbg.generated Thu Jan 24 11:47:13 CST 2019
     */
    int updateByExampleSelective(@Param("record") SupershortForecHis record, @Param("example") SupershortForecHisExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table supershort_forec_his
     *
     * @mbg.generated Thu Jan 24 11:47:13 CST 2019
     */
    int updateByExample(@Param("record") SupershortForecHis record, @Param("example") SupershortForecHisExample example);
}