package com.fwzx.photovoltaicdatacollect.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.fwzx.photovoltaicdatacollect.pojo.SuperaccuPassRate;
import com.fwzx.photovoltaicdatacollect.pojo.SuperaccuPassRateExample;

public interface SuperaccuPassRateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table superaccu_pass_rate
     *
     * @mbg.generated Tue Jan 29 15:22:02 CST 2019
     */
    long countByExample(SuperaccuPassRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table superaccu_pass_rate
     *
     * @mbg.generated Tue Jan 29 15:22:02 CST 2019
     */
    int deleteByExample(SuperaccuPassRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table superaccu_pass_rate
     *
     * @mbg.generated Tue Jan 29 15:22:02 CST 2019
     */
    int insert(SuperaccuPassRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table superaccu_pass_rate
     *
     * @mbg.generated Tue Jan 29 15:22:02 CST 2019
     */
    int insertSelective(SuperaccuPassRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table superaccu_pass_rate
     *
     * @mbg.generated Tue Jan 29 15:22:02 CST 2019
     */
    List<SuperaccuPassRate> selectByExample(SuperaccuPassRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table superaccu_pass_rate
     *
     * @mbg.generated Tue Jan 29 15:22:02 CST 2019
     */
    int updateByExampleSelective(@Param("record") SuperaccuPassRate record, @Param("example") SuperaccuPassRateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table superaccu_pass_rate
     *
     * @mbg.generated Tue Jan 29 15:22:02 CST 2019
     */
    int updateByExample(@Param("record") SuperaccuPassRate record, @Param("example") SuperaccuPassRateExample example);

    int updateSuperPassRateByDateTime(@Param("apr") SuperaccuPassRate apr);

    SuperaccuPassRate selectByDataTime(@Param("dataTime") String dataTime);
    
    int updateSuperAccuRateByDateTime(@Param("apr") SuperaccuPassRate apr);
}